# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: evaluation center
email: youremail@email.com
project: Evaluation Center

description: This is my site for my thing!

baseurl: ""     # the subpath of your site, e.g. /blog
url: "https://ec-center.netlify.com" # the base hostname & protocol for your site, e.g. http://example.com

collections:
  guide:
    output: true
  sections:


defaults:
  - scope:
      path: ""
      type: guide
    values:
      layout: page
  - scope:
      path: ""
      type: pages
    values:
      layout: page

google_analytics: ""

sass:
    load_paths:
        - _sass
        - node_modules

environment: prod

# Build settings
markdown: kramdown
livereload: true     # You no longer need to include --livereload
reload_port: 5678    # If you don't want to use the default port
gems:
  - jekyll-feed
exclude: [package.json, npm-debug.log, Gruntfile.js, Gemfile, Gemfile.lock]
